name: demo_bloc_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^1.0.0
  scoped_model: ^1.0.1
  flutter_bloc: ^1.0.0
  provider: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=1.3.0 <2.0.0"


flutter:

  uses-material-design: true
